# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rcdnrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Active'), ('2', 'Suspended')], max_length=1)),
                ('plan', models.CharField(choices=[('0', 'Basic'), ('1', 'Pro')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('tid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=6)),
                ('message', models.CharField(max_length=600)),
                ('status', models.CharField(choices=[('0', 'Open'), ('1', 'Closed')], max_length=1)),
                ('reply', models.CharField(max_length=600)),
                ('updatetime', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
